GET http://localhost:3000/api/articles HTTP/1.1

###
GET http://localhost:3000/api/articles/<> HTTP/1.1

###

GET http://localhost:3000/api/categories HTTP/1.1

###

POST http://localhost:3000/api/articles HTTP/1.1
content-type: application/json

{
    "category": [
        "Test Create 1",
        "Test Create 2"
    ],
    "title": "Test Create Title 30 symbols long at least",
    "announce": "Test Create Announcement 30 symbols long at least",
    "fullText": "Test Create"
}


###

PUT http://localhost:3000/api/articles/<> HTTP/1.1
content-type: application/json

{
    "category": [
        "Test Edit 1",
        "Test Edit 2"
    ],
    "title": "Test Edit Title 30 symbols long at least",
    "announce": "Test Edit Announcement 30 symbols long at least",
    "fullText": "Test Edit"
}

###

DELETE http://localhost:3000/api/articles/<> HTTP/1.1

###

GET http://localhost:3000/api/articles/<>/comments HTTP/1.1

###

DELETE http://localhost:3000/api/articles/<>/comments/<> HTTP/1.1

###

POST http://localhost:3000/api/articles/<>/comments HTTP/1.1
content-type: application/json

{
    "text": "Comment Text at least 30 characters long"
}

###

GET http://localhost:3000/api/search?query=Учим HTML и CSS


